name: Codecov
on:
  push:
    branches:
      - master # Default release branch
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Codecov
        id: codecov
        uses: codecov/codecov-action@v1.0.7

