name: Codecov
on:
  push:
    branches:
      - master # Default release branch
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
       - uses: codecov/codecov-action@v1.0.7
       - name: Utapau
